language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
    - sudo /etc/init.d/apache2 restart
    - composer self-update
    - composer install --dev --prefer-source
    - chmod -R 777 ./

script:
    - phpunit -c ./